spring:
  application:
    name: ruichen-restful
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #    未集成log4jdbc
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zif_app?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username: dev_owner
    password: ziroomdb
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    druid:
      initial-size: 5
      min-idle: 1
      max-active: 200
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,slf4j
      filter:
        stat:
          merge-sql: true
          log-slow-sql: true
          slow-sql-millis: 2000
        slf4j:
          statement-executable-sql-log-enable: true
          statement-execute-after-log-enabled: true
          statement-log-error-enabled: true
      #监控页面
      stat-view-servlet:
        #开启/关闭
        enabled: true
        #登录账号和密码
        login-username: admin
        login-password: 123456
        #是否能够重置数据
        reset-enable: false
        #白名单
        allow: 192.168.1-255
        #IP黑名单 (存在共同时，deny优先于allow) : 如果满足deny的话提示:Sorry, you are not permitted to view this page.
        deny: 127.0.0.2
      web-stat-filter:
        #添加不需要忽略的格式信息
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
